### ISSUE TITLE
Feature: Option to use the right Stick

### ISSUE THREAD

**Issue by WyvernIXTL** [cakama3a/Gamepadla#14]
I accidentally put glue into my left stick. I then had to buy a new controller.

It'd be nice to have the option to test with the right stick instead.

**Comment by cakama3a** [comment]
Absolutely no problem, I will do it in the next update.

**Comment by cakama3a** [comment]
Done!

**Comment by WyvernIXTL** [comment]
Many thanks 🙏

*(Really interesting: My new controller has 7ms latency with Bluetooth 5.0 while my old controller with 2.4 GHz dongle has 26ms latency. I am really impressed with Bluetooth latency improvements.)*
