### ISSUE TITLE
REQUEST: Overclocked DualSense and DualSense Edge Tests

### ISSUE THREAD

**Issue by rajohns08** [cakama3a/Gamepadla#3]

**Comment by adamtenna** [comment]
specifically over a wired connection

**Comment by SeeThruHead** [comment]
i uploaded a ds edge test
it was 700hz bluetooth
think it's still under moderation

**Comment by cakama3a** [comment]
Look under the polling tab, as this is a software test https://gamepadla.com/post/sony-dualsense-edge.html#latency

**Comment by rajohns08** [comment]
@cakama3a thanks I see the overclocked polling test. Any chance you could do the GPDL overclock test?

**Comment by rajohns08** [comment]
Closing to put this in the proper GPDL repo: https://github.com/cakama3a/GPDL/issues/2
